# Simple Neural Network

In [11]:
from sklearn import datasets
import numpy as np

X_data = np.array([[0.4,0.3],[0.6,0.8],[0.7,0.5],[0.9,0.2]])
Y_data = np.array([[1],[1],[1],[0]])

"""
0.4  0.3   1
0.6  0.8   1
0.7  0.5   1
0.9  0.2   0
"""

X = X_data.T
Y = Y_data.T

W = np.zeros((X.shape[0], 1))
b = 0

num_samples = float(X.shape[1])
for i in range(2000):
    Z = np.dot(W.T,X) + b
    pred_y = 1/(1 + np.exp(-Z)) #Sigmoid Activation  Function
    if(i%100 == 0):
      print("cost after %d epoch:"%i)# printing the Cost Fuunction
      print (-1/num_samples *np.sum(Y*np.log(pred_y) + (1-Y)*(np.log(1-pred_y)))) # Applying the cost function to the logistic regression
        #---------------------Back Ward Propogation --------------------
    dW = (np.dot(X,(pred_y-Y).T))/num_samples
    db = np.sum(pred_y-Y)/num_samples
    W = W - (0.1 * dW) # 0.1 hyperparamer
    b = b - (0.1 * db)

print("The final Weight and Loss")
print (W,b)

cost after 0 epoch:
0.6931471805599453
cost after 100 epoch:
0.5020586179991661
cost after 200 epoch:
0.4448439151612328
cost after 300 epoch:
0.3979115275585397
cost after 400 epoch:
0.3590456846967789
cost after 500 epoch:
0.32654805177827606
cost after 600 epoch:
0.2990946818904699
cost after 700 epoch:
0.27566689061159727
cost after 800 epoch:
0.25548229634006936
cost after 900 epoch:
0.2379373586492477
cost after 1000 epoch:
0.2225628943911951
cost after 1100 epoch:
0.20899075448733584
cost after 1200 epoch:
0.1969291871801246
cost after 1300 epoch:
0.18614467111915223
cost after 1400 epoch:
0.17644847640779723
cost after 1500 epoch:
0.1676866592266118
cost after 1600 epoch:
0.15973255199801517
cost after 1700 epoch:
0.15248107596905414
cost after 1800 epoch:
0.14584439396391574
cost after 1900 epoch:
0.13974855674512077
The final Weight and Loss
[[-5.41785857]
 [ 6.45588012]] 2.3882958084750783


# Simple Neural Network

In [1]:

from sklearn import datasets
import numpy as np


In [2]:
X_data = np.array([[0.4,0.3],[0.6,0.8],[0.7,0.5],[0.9,0.2]])
Y_data = np.array([[1],[1],[1],[0]])

In [3]:
X_data

array([[0.4, 0.3],
       [0.6, 0.8],
       [0.7, 0.5],
       [0.9, 0.2]])

In [49]:
X_data.shape

(4, 2)

In [50]:
Y_data = np.array([[1],[1],[1],[0]])

In [51]:
Y_data.shape

(4, 1)

In [4]:
X = X_data.T
Y = Y_data.T

In [5]:
X

array([[0.4, 0.6, 0.7, 0.9],
       [0.3, 0.8, 0.5, 0.2]])

In [6]:
Y

array([[1, 1, 1, 0]])

In [7]:
X_data.shape

(4, 2)

In [8]:
Y_data.shape

(4, 1)

In [58]:
#row1 *columns1
#row2 *columns2

#columns1 === rows2

In [59]:
X.shape

(2, 4)

In [60]:
X[0]

array([0.4, 0.6, 0.7, 0.9])

In [61]:
X.shape[0]

2

In [9]:

W = np.zeros((X.shape[0], 1)) # W = np.zeros((2, 1))
b = 0


In [10]:
t = np.zeros((2,1))
t

array([[0.],
       [0.]])

In [63]:
W

array([[0.],
       [0.]])

In [64]:
W.shape

(2, 1)

In [65]:
num_samples = float(X.shape[1])

In [66]:
print(num_samples)

4.0


In [67]:
W.T

array([[0., 0.]])

In [68]:
W.T.shape

(1, 2)

In [69]:
X_data.shape

(4, 2)

# Questions To be Clarified