# Step : 1 importing the Libraries

In [1]:
import numpy as np
import pandas as pd

# Step 2 : Reading the Dataset

In [2]:
dataset = pd.read_csv("cancer_dataset.csv")

In [4]:
dataset.head(7)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   
5    843786         M        12.45         15.70           82.57      477.1   
6    844359         M        18.25         19.98          119.60     1040.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   
5          0.12780           0.17000          0.1578              0.08089   
6          0.09463           0.10900          0.1127              0.07400   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   
5  ...          23.75           103.40       741.6            0.1791   
6  ...          27.66           153.20      1606.0            0.1442   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   
5             0.5249           0.5355                0.1741          0.3985   
6             0.2576           0.3784                0.1932          0.3063   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  
5                  0.12440          NaN  
6                  0.08368          NaN  

[7 rows x 33 columns]

In [15]:
x = dataset.iloc[:,2:32]
y = dataset.iloc[:,1]

print(y.head(3))
print("********")
print(x.ndim)
print(y.ndim)

0    M
1    M
2    M
Name: diagnosis, dtype: object
********
2
1


# Step 3 : Seperating the Features and Target

In [4]:
x = dataset[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]

In [5]:
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [6]:
y = dataset["Species"]

In [7]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

# Step 4 : Splitting the dataset into training set and test set

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8 ,random_state=-42)

ValueError: Seed must be between 0 and 2**32 - 1

# Step 5: Creating the Model

In [9]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

# Step 6 : Training the Model

In [10]:
model.fit(x_train,y_train)

LogisticRegression()

# Step 7 : Testing the Model

In [11]:
model.predict([[5.1,3.5	,1.4,0.2]])

C:\Users\Siva\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)

In [12]:
y_pred = model.predict(x_test)

# Step 8: Checking the Accuracy Score

In [13]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred)
print(acc*100)

100.0


# Step 9 : Create Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [21]:
from sklearn.model_selection import train_test_split

# Example data
X = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
y = [0, 1, 0, 1, 0]

# Split data without specifying random_state
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print("X_train:", X_train)
print("X_test:", X_test)
print("y_train:", y_train)
print("y_test:", y_test)


X_train: [[5, 6], [1, 2], [7, 8], [3, 4]]
X_test: [[9, 10]]
y_train: [0, 0, 1, 1]
y_test: [0]
